info_buttons= {

'Liveability' : 'This measure shows how liveable each sector in the city is likely to be. The liveability index consists of 4 KPIs:\n1. Access do schools \n2. Distance to parks \n3. Vibrancy \n4. Access to cultural facilities',
'Vibrancy': 'This measure shows the potential for vibrant streets, based on multi-scale accessibility (citywide and local scale spatial accessibility). Vibrant places can foster economic activity and social encounter.',
'Access to education': 'This measure shows how many educational facilities can be accessed within the specified time and mode of travel.',
'nurseries': 'This measure shows how many nurseries can be accessed within the specified time and mode of travel.',
'primary & secondary education': 'This measure shows how many primary and secondary schools can be accessed within the specified time and mode of travel.',
'higher education faculties': 'This measure shows how many higher education faculties can be accessed within the specified time and mode of travel.',
'Access to parks': 'This measure shows how many parks can be accessed within the specified time and mode of travel.',
'Access to cultural facilities': 'This measure shows how many cultural facilities can be accessed within the specified time and mode of travel.',
'Health': 'This measure shows how well each sector performs against a combined healthy index. The health index consists of 5 KPIs: \n1. Access to health care \n2. Walkability \n3. Car dependence \n4.Access to sport facilities \n5. Access to public transport',
'Access to sport facilities': 'This measure shows how many sports facilities can be accessed within the specified time and mode of travel.',
'Access to healthcare': 'This measure shows how many healthcare facilities can be accessed within the specified time and mode of travel.',
'primary healthcare facilites': 'This measure shows how many primary healthcare facilities can be accessed within the specified time and mode of travel.',
'secondary healthcare facilites': 'This measure shows how many secondary healthcare facilities can be accessed within the specified time and mode of travel.',
'Access to public transport': 'This measure shows how many bus stops can be accessed within 10 minutes walking.',
'Car dependence': 'This measure shows the ratio between number of jobs reached in 30 min trip by car compared to those reached by public transport.',
'Walkability': 'This measure shows the ease of access to mix-use urban centres. This translates into how many different land-uses can be accessed within 5 minutes of walking.',
'Sustainability': 'This measure shows how well each sector in the city performs against a sustainability index. The index is based on the energy demand of each building weighted by the population living in each sector.',
#'Population': 'This measure shows the population living in each district of Nur-Sultan',
'Energy consumption': 'Heating demand per building.',
'Combined': 'This measure shows how well each sector in the city performs against all KPIs; Liveability, Sustainability and Health.',
'Global choice': 'This measure shows street network accessibility at citywide scale. The higher the accessibility value, the more likely it is for a street to be used as a through route between an origin and a destination.',
'Local choice': 'This measure shows street network accessibility at local scale. The higher the accessibility value, the more likely it is for a street to be used as a through route between an origin and a destination.',
'Global integration': 'This measure shows street network centrality at citywide scale. The higher the centrality value, the more likely it is for a street to be used as a destination.',
'Local integration': 'This measure shows street network centrality at  local scale. The higher the centrality value, the more likely it is for a street to be used as a destination.',
'Transformability index': 'This measure shows the ability of each building in Nur-Sultan to be transformed. This is a combined measure that takes into account: \n1. Land Use \n2. Floor area \n3 Material \n4. Number of floors.',
'potential plots': ''
}