info_buttons= {




'Liveability ' : 'This measure shows how well each district in the city performs against a combined Liveability index created by combining KPIs. These KPIs include 1. Access do schools; 2. Distance to parks; 3. Vibrancy; 4. Access to cultural facilities',
'Vibrancy ': 'The map shows the buildings located in streets that, by performing well in both citywide and local scale spatial accessibility, have the potential to become vibrant streets and foster economic activity and social encounter.',
'Access to Schools ': 'This measure shows how many Educational facilities in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Nurseries': 'This measure shows how many Nurseries in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Primary and Secondary Schools': 'This measure shows how many Primary/ Secondary schools in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Higher Education ': 'This measure shows how many Higher Education facilities in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Parks ': 'This measure shows how many Parks in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Cultural Facilities': 'This measure shows how many Cultural facilities in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Schools ': 'This measure shows how many Educational facilities in Nur-Sultan can be accessed within 15-minute bus ride.',
'Access to Nurseries': 'This measure shows how many Nurseries in Nur-Sultan can be accessed within 15-minute bus ride.',
'Access to Primary and Secondary Schools': 'This measure shows how many Primary/ Secondary facilities in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Higher Education ': 'This measure shows how many Higher Education facilities in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Parks ': 'This measure shows how many Parks in Nur-Sultan can be accessed within 15-minute bus ride.',
'Access to Cultural Facilities': 'This measure shows how many Cultural facilities in Nur-Sultan can be accessed within 15-minute bus ride.',
'Access to Schools ': 'This measure shows how many Educational facilities in Nur-Sultan can be accessed within 15-minute car ride.',
'Access to Nurseries': 'This measure shows how many Nurseries in Nur-Sultan can be accessed within 15-minute car ride.',
'Access to Primary and Secondary Schools': 'This measure shows how many Primary/ Secondary schools in Nur-Sultan can be accessed within 15-minute car ride.',
'Access to Higher Education ': 'This measure shows how many Higher Education facilities in Nur-Sultan can be accessed within 15-minute car ride.',
'Access to Cultural Facilities': 'This measure shows how many Cultural facilities in Nur-Sultan can be accessed within 15-minute car ride.',
'Health': 'This measure shows how well each district in the city performs against a combined Healthy City index created by combining KPIs. These KPIs include: 1. Access to health care; 2. Walkability 3. Car dependence 4. Access to sport facilities 5. Access to public transport',
'Access to Sport Facilities': 'This measure shows how many Sports facilities in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Healthcare': 'This measure shows how many Healthcare facilities in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Primary care': 'This measure shows how many Primary Healthcare facilities in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Secondary care': 'This measure shows how many Secondary Healthcare facilities in Nur-Sultan can be accessed within 10-minute walk.',
'Access to Public Transport': 'This measure shows how many bus stops in Nur-Sultan can be accessed within 10-minute walk.',
'Car dependence': 'This measure shows the ratio between number of jobs reached in 30-min trip by car compared to those reached by public transport.',
'Walkability ': 'This measure shows the ease of access to mix-use urban centres. This translates into how many different land-uses can be accessed in Nur-Sultan within 5-minute walk.',
'Access to Sport Facilities': 'This measure shows how many Sports facilities in Nur-Sultan can be accessed within 15-minute bus ride.',
'Access to Healthcare': 'This measure shows how many Healthcare facilities in Nur-Sultan can be accessed within 15-minute bus ride.',
'Access to Primary care': 'This measure shows how many Primary Healthcare facilities in Nur-Sultan can be accessed within 15-minute bus ride.',
'Access to Secondary care': 'This measure shows how many Secondary Healthcare facilities in Nur-Sultan can be accessed within 15-minute bus ride.',
'Access to Sport Facilities': 'This measure shows how many Sports facilities in Nur-Sultan can be accessed within 15-minute car ride.',
'Access to Healthcare': 'This measure shows how many Healthcare facilities in Nur-Sultan can be accessed within 15-minute car ride.',
'Access to Primary care': 'This measure shows how many Primary Healthcare facilities in Nur-Sultan can be accessed within 15-minute car ride.',
'Access to Secondary care': 'This measure shows how many Secondary Healthcare facilities in Nur-Sultan can be accessed within 15-minute car ride.',
'Sustainability': 'This measure shows how well each district in the city performs against a combined Sustainability index created by combining the energy demand of each building with the population living in each district.',
'Population': 'This measure shows the population living in each district of Nur-Sultan',
'Energy consumption ': 'Heating demand per building in Nur-Sultan.',
'Combined': 'This measure shows how well each district in the city performs against all KPIs for Liveability, Sustainability and Healthy City.',
'Normalized Choice 10,000': 'This measure shows street network accessibility at citywide scale. The higher the accessibility value, the more likely it is for a street to be used as a through route between an origin and a destination.',
'Normalized Choice 2,000': 'This measure shows street network accessibility at local scale. The higher the accessibility value, the more likely it is for a street to be used as a through route between an origin and a destination.',
'Integration 10,000': 'This measure shows street network centrality at citywide scale. The higher the centrality value, the more likely it is for a street to be used as a destination.',
'Integration 2,000': 'This measure shows street network centrality at  local scale. The higher the centrality value, the more likely it is for a street to be used as a destination.',
'transformability index': 'This measure shows the ability of each building in Nur-Sultan is to be transformed. This is a combined measure that takes into account: 1. Land Use; 2. FAR; 3 Material; 4. Number of floors.'
}